"""Scan output: terminal table, Markdown and JSON."""

from __future__ import annotations

import json

from pqc_kit import __version__
from pqc_kit.model import STATUS_ORDER, STATUS_TEXT, ScanResult

SCAN_SCHEMA = "https://github.com/dynamohtech/pqc-kit/schemas/scan-v1"


def summary_line(result: ScanResult) -> str:
    c = result.counts()
    parts = [f"{c[s]} {STATUS_TEXT[s].lower()}" for s in STATUS_ORDER if c[s]]
    kinds = ", ".join(f"{n} {k}" for k, n in result.files_by_kind.items())
    tests = sum(1 for f in result.findings if f.in_tests)
    text = (f"Scanned {result.files_scanned} files ({kinds or 'none with cryptography'}): "
            f"{len(result.findings)} findings" + (f" ({', '.join(parts)})" if parts else "") + ".")
    if tests:
        text += f" {tests} {'is' if tests == 1 else 'are'} in test code."
    return text


def to_json(result: ScanResult) -> str:
    data = {
        "$schema": SCAN_SCHEMA,
        "tool": {"name": "pqc-kit", "version": __version__},
        "root": result.root,
        "files_scanned": result.files_scanned,
        "files_by_kind": result.files_by_kind,
        "summary": result.counts(),
        "findings": [f.to_dict() for f in result.findings],
        "errors": result.errors,
    }
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def to_table(result: ScanResult, width: int = 60) -> str:
    lines = [summary_line(result), ""]
    if not result.findings:
        lines.append("No cryptography found.")
        return "\n".join(lines) + "\n"
    rows = [("STATUS", "ALGORITHM", "WHERE", "FOUND BY")]
    for f in result.findings:
        where = f.where + (" (test)" if f.in_tests else "")
        rows.append((STATUS_TEXT[f.status], f.name, where, _clip(f.symbol, width)))
    widths = [max(len(r[i]) for r in rows) for i in range(3)]
    for r in rows:
        lines.append(f"{r[0]:<{widths[0]}}  {r[1]:<{widths[1]}}  {r[2]:<{widths[2]}}  {r[3]}".rstrip())
    if result.errors:
        lines += ["", f"{len(result.errors)} item(s) could not be read (often truncated examples in docs or tests); "
                      "--format json lists them."]
    lines += ["", "Run `pqc-kit assess` for the deadlines that apply, or `pqc-kit cbom` for a CycloneDX CBOM."]
    return "\n".join(lines) + "\n"


def to_markdown(result: ScanResult) -> str:
    out = [f"# Cryptography inventory: `{result.root}`", "", summary_line(result), ""]
    for status in STATUS_ORDER:
        items = [f for f in result.findings if f.status == status]
        if not items:
            continue
        out += [f"## {STATUS_TEXT[status]} ({len(items)})", "", "| Algorithm | Where | Found by | Why |",
                "| --- | --- | --- | --- |"]
        for f in items:
            where = f"`{f.where}`" + (" (test)" if f.in_tests else "")
            why = " ".join(f.reasons[:1] + f.notes[:1])
            out.append(f"| {_md(f.name)} | {where} | `{_md(_clip(f.symbol, 60))}` | {_md(why)} |")
        out.append("")
    if result.errors:
        out += ["## Files that could not be fully read", ""] + [f"- {_md(e)}" for e in result.errors] + [""]
    out.append(f"_Generated by pqc-kit {__version__}._")
    return "\n".join(out) + "\n"


def _clip(s: str, n: int) -> str:
    return s if len(s) <= n else s[: n - 1] + "…"


def _md(s: str) -> str:
    return str(s).replace("|", "\\|").replace("\n", " ")
